// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rec_Tracker.Data;

#nullable disable

namespace Rec_Tracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250722092108_InitRecDetailsSchema")]
    partial class InitRecDetailsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Rec_Tracker.Models.Rec_Details", b =>
                {
                    b.Property<int>("File_Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("File_Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("File_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("File_Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Organisation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Row_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Shelf_Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("File_Number");

                    b.ToTable("Record_details");
                });
#pragma warning restore 612, 618
        }
    }
}
